local_backend: true

backend:
  name: git-gateway
  squash_merges: true
  branch: demo

media_folder: static/img
public_folder: /img

search: false

collections:
  - name: "quiz"
    label: "quiz"
    folder: "content/quiz"
    create: true
    slug: "{{slug}}"
    widget: object
    editor:
      preview: false
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          pattern: ["^.{0,100}$", "Must have maximum 100 characters"],
          hint: "Max 100 characters",
        }
      - {
          label: "Title Mobile",
          name: "title_mobile",
          widget: "string",
          hint: "Shorter title to be displayed on mobile devices. If not provided, normal title will be used. Max 60 characters.",
          pattern: ["^.{0,60}$", "Must have maximum 60 characters"],
        }
      - {
          default: 180,
          label: "Time (seconds)",
          name: "time",
          widget: "number",
          min: 1,
        }
      - label: "Subcategories"
        label_singular: "Subcategory"
        name: "subcategories"
        widget: "list"
        min: 1
        max: 99
        required: true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Answers"
            label_singular: "answer"
            name: "answers"
            min: 1
            max: 99
            widget: "list"
            fields:
              - { label: "Value", name: "value", widget: "string" }
