# local_backend: true

backend:
  name: git-gateway
  squash_merges: true

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

search: false

collections:
  - name: 'content'
    label: 'content'
    folder: 'content/content'
    create: true
    delete: false
    slug: '{{slug}}'
    widget: object
    editor:
      preview: false
    fields:
      - label: 'Quizzes'
        label_singular: 'Quiz'
        name: 'quiz'
        widget: list
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - label: 'Subcategories'
            label_singular: 'Subcategory'
            name: 'subcategory'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - label: 'Answers'
                label_singular: 'answer'
                name: 'answer'
                widget: 'list'
                fields: 
                  - { label: 'Value', name: 'value', widget: 'string' }
